// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bowling_tournament_MVCPRoject.Persistence;

#nullable disable

namespace bowling_tournament_MVCPRoject.Migrations
{
    [DbContext(typeof(BowlingDbContextV2))]
    partial class BowlingDbContextV2ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("bowling_tournament_MVCPRoject.Domain.Entities.BowlingUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BowlingUser", (string)null);
                });

            modelBuilder.Entity("bowling_tournament_MVCPRoject.Domain.Entities.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DivisionId");

                    b.HasIndex("DivisionId")
                        .IsUnique();

                    b.ToTable("Division", (string)null);
                });

            modelBuilder.Entity("bowling_tournament_MVCPRoject.Domain.Entities.PlayerV2", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("bowling_tournament_MVCPRoject.Domain.Entities.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistrationId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Registration", (string)null);
                });

            modelBuilder.Entity("bowling_tournament_MVCPRoject.Domain.Entities.TeamV2", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RegistrationPaid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamDivision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DivisionId");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamDivision");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("bowling_tournament_MVCPRoject.Domain.Entities.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RegistrationOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TournamentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TournamentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WatcherCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("TournamentId");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.ToTable("Tournament", (string)null);
                });

            modelBuilder.Entity("bowling_tournament_MVCPRoject.Domain.Entities.PlayerV2", b =>
                {
                    b.HasOne("bowling_tournament_MVCPRoject.Domain.Entities.TeamV2", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("bowling_tournament_MVCPRoject.Domain.Entities.TeamV2", b =>
                {
                    b.HasOne("bowling_tournament_MVCPRoject.Domain.Entities.Division", null)
                        .WithMany()
                        .HasForeignKey("TeamDivision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Team_Division");
                });
#pragma warning restore 612, 618
        }
    }
}
